name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, macos-10.15]
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: "14.15.0"
        
        - name: Check out repository code
          uses: actions/checkout@v3
        - run: npm install 

        - name: build windows app
          if: matrix.os == 'windows-2019'
          run: |
            npm run package-win
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: build mac app
          if: matrix.os == 'macos-10.15'
          run: |
            npm run package-mac
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
        # step5: cleanup artifacts in dist_electron
        - name: cleanup artifacts for windows
          if: matrix.os == 'windows-2019'
          run: |
            npx rimraf "dist/!(*.exe)"

        - name: cleanup artifacts for macosZ
          if: matrix.os == 'macos-10.15'
          run: |
            npx rimraf "dist/!(*.dmg)"
        
        # step6: upload artifacts
        - name: upload artifacts
          uses: actions/upload-artifact@v2
          with:
            name: ${{ matrix.os }}
            path: dist

        # step7: create release
        - name: release
          uses: softprops/action-gh-release@v1
          if: startsWith(github.ref, 'refs/tags/')
          with:
            files: "dist/**"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}