name: Test Job
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
            uses: actions/checkout@master
            
            - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
                node-version: '14.15.0'
            - run: npm run init
            - run: npm run build --if-present

            - name: checkout
              uses: actions/checkout@master
            - name: install script
              run: npm install
            - name: package win
              run: npm run package-win
            - name: package mac
              run: npm run package-win
            - name: ls script
              run: ls la dist