name: Test Job
on: push
jobs:
    test_job:
        name: My first job
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@master
            - name: install script
              run: npm install
